# Generated by Django 3.1.5 on 2021-01-17 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20210115_0400'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_category',
            field=models.CharField(default='others', max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='item_desc',
            field=models.CharField(default='Best deal offered', max_length=500),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.ImageField(blank=True, null=True, upload_to='upload/'),
        ),
    ]
